import type { Metadata } from "next";

import { site } from "@/lib/site";

type OgImage = { url: string; width: number; height: number; alt: string };

type PageMeta = {
  title: string;
  description: string;
  path: string;
  image?: OgImage;
};

// Generated by app/opengraph-image.tsx. Child `openGraph` objects replace the parent's
// entirely, so every page has to list its image explicitly.
const defaultImage: OgImage = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "Himidi Graphics: graphic design and branding studio in Tanzania",
};

/** Per-page metadata with its own canonical URL, Open Graph and Twitter fields. */
export function pageMetadata({ title, description, path, image = defaultImage }: PageMeta): Metadata {
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      locale: "en_TZ",
      siteName: site.name,
      url: path,
      title: `${title} | ${site.name}`,
      description,
      images: [image],
    },
    twitter: {
      card: "summary_large_image",
      title: `${title} | ${site.name}`,
      description,
      images: [image.url],
    },
  };
}
